[package]
name = "kaiko_stream"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
prost = "0.13.3"
prost-types = "0.13.3"
tokio = { version = "1.41.1", features = ["full"] }
tonic = { version = "0.12.3", features = ["tls"] }

[build-dependencies]
tonic-build = "0.12.3"
